const fs = require("fs");
const inquirer = require("inquirer");

inquirer
  .prompt([
    {
      type: "input",
      message: "What is your team manager's name?",
      name: "manager",
    },
    {
      type: "input",
      message: "What is your employee ID?",
      name: "ID",
    },
    {
      type: "input",
      message: "What is your name?",
      name: "name",
    },
    {
      type: "input",
      message: "Where do you live?",
      name: "location",
    },
    {
      type: "input",
      message: "What is your email?",
      name: "email",
    },
    {
      type: "input",
      message: "What is your GitHub username?",
      name: "github",
    },
  ])
  .then((response) => {
    fs.writeFile(
      "index.html",
      `<!DOCTYPE html>
    <html lang="en-US">
    
    <head>
      <meta charset="UTF-8">
      <title>Mini Project</title>
    </head>
    
    <body>
      <header>
        <h1>Generated by node.js</h1>
      </header>
      <main>
        <h2>${response.name}</h2>
        <h2>${response.location}</h2>
        <h2>${response.bio}</h2>
        <h2>${response.linkedin}</h2>
        <h2>Email: <a href="mailto:${response.email}">${response.email}</a></h2>
        <h2>Github: <a href="https://github.com/${response.github}">${response.github}</a></h2>
      </main>
    </body>    
    `,
      (err) => (err ? console.error(err) : console.log("Commit logged!"))
    );
  });
